-- Matched 38 patients out of unique CSV entries
BEGIN;
UPDATE patients SET patient_id = patient_id || '_TMP' WHERE clinic_id = (SELECT id FROM clinics WHERE owner_email = 'zaheeneqbal@gmail.com');
UPDATE patients SET patient_id = 'PID-1' WHERE id = 2;
UPDATE patients SET patient_id = 'PID-2' WHERE id = 13;
UPDATE patients SET patient_id = 'PID-3' WHERE id = 4;
UPDATE patients SET patient_id = 'PID-4' WHERE id = 21;
UPDATE patients SET patient_id = 'PID-5' WHERE id = 20;
UPDATE patients SET patient_id = 'PID-6' WHERE id = 1;
UPDATE patients SET patient_id = 'PID-7' WHERE id = 9;
UPDATE patients SET patient_id = 'PID-8' WHERE id = 19;
UPDATE patients SET patient_id = 'PID-9' WHERE id = 15;
UPDATE patients SET patient_id = 'PID-10' WHERE id = 5;
UPDATE patients SET patient_id = 'PID-11' WHERE id = 16;
UPDATE patients SET patient_id = 'PID-13' WHERE id = 26;
UPDATE patients SET patient_id = 'PID-14' WHERE id = 10;
UPDATE patients SET patient_id = 'PID-16' WHERE id = 17;
UPDATE patients SET patient_id = 'PID-17' WHERE id = 24;
UPDATE patients SET patient_id = 'PID-18' WHERE id = 8;
UPDATE patients SET patient_id = 'PID-12' WHERE id = 23;
UPDATE patients SET patient_id = 'PID-19' WHERE id = 7;
UPDATE patients SET patient_id = 'PID-20' WHERE id = 6;
UPDATE patients SET patient_id = 'PID-21' WHERE id = 27;
UPDATE patients SET patient_id = 'PID-21' WHERE id = 27;
UPDATE patients SET patient_id = 'PID-23' WHERE id = 11;
UPDATE patients SET patient_id = 'PID-24' WHERE id = 14;
UPDATE patients SET patient_id = 'PID-25' WHERE id = 35;
UPDATE patients SET patient_id = 'PID-26' WHERE id = 22;
UPDATE patients SET patient_id = 'PID-27' WHERE id = 28;
UPDATE patients SET patient_id = 'PID-28' WHERE id = 36;
UPDATE patients SET patient_id = 'PID-29' WHERE id = 37;
UPDATE patients SET patient_id = 'PID-30' WHERE id = 34;
UPDATE patients SET patient_id = 'PID-31' WHERE id = 25;
UPDATE patients SET patient_id = 'PID-32' WHERE id = 33;
UPDATE patients SET patient_id = 'PID-33' WHERE id = 31;
UPDATE patients SET patient_id = 'PID-34' WHERE id = 12;
UPDATE patients SET patient_id = 'PID-35' WHERE id = 30;
UPDATE patients SET patient_id = 'PID-36' WHERE id = 38;
UPDATE patients SET patient_id = 'PID-37' WHERE id = 18;
UPDATE patients SET patient_id = 'PID-38' WHERE id = 29;
UPDATE patients SET patient_id = 'PID-39' WHERE id = 32;
COMMIT;
