import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { Patient, Visit } from '@/types';

interface ClinicInfo {
  clinic_name: string;
  owner_name: string;
  phone: string;
  address: string;
  email: string;
}

export const generatePrescriptionPDF = (patient: Patient, clinic: ClinicInfo, visit?: Visit) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header - Clinic Info
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235); // primary color #2563eb
  doc.setFont('helvetica', 'bold');
  doc.text(clinic.clinic_name || 'IntelliDent Clinic', pageWidth / 2, 20, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // gray-500
  doc.setFont('helvetica', 'normal');
  const clinicSubHeader = `${clinic.address || ''}${clinic.phone ? ' | Phone: ' + clinic.phone : ''}${clinic.email ? ' | Email: ' + clinic.email : ''}`;
  doc.text(clinicSubHeader, pageWidth / 2, 28, { align: 'center' });

  // Line separator
  doc.setDrawColor(229, 231, 235);
  doc.line(15, 35, pageWidth - 15, 35);

  // Patient Info
  doc.setFontSize(12);
  doc.setTextColor(17, 24, 39); // gray-900
  doc.setFont('helvetica', 'bold');
  doc.text('PATIENT INFORMATION', 15, 45);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Name: ${patient.name}`, 15, 52);
  doc.text(`Age/Gender: ${patient.age}Y / ${patient.gender}`, 15, 58);
  doc.text(`Patient ID: ${patient.patient_id}`, 15, 64);
  
  const date = visit?.date || patient.date;
  const doctor = visit?.doctor || patient.doctor || clinic.owner_name || 'N/A';
  
  doc.text(`Date: ${new Date(date).toLocaleDateString()}`, pageWidth - 15, 52, { align: 'right' });
  doc.text(`Doctor: ${doctor}`, pageWidth - 15, 58, { align: 'right' });

  if (visit?.tooth_number) {
    doc.text(`Tooth: ${visit.tooth_number}`, pageWidth - 15, 64, { align: 'right' });
  }

  // Clinical Details
  if (visit?.symptoms || visit?.diagnosis || visit?.treatment_done) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('CLINICAL DETAILS', 15, 75);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    let currentY = 81;
    if (visit.symptoms) {
        doc.text(`Symptoms: ${visit.symptoms}`, 15, currentY);
        currentY += 6;
    }
    if (visit.diagnosis) {
        doc.text(`Diagnosis: ${visit.diagnosis}`, 15, currentY);
        currentY += 6;
    }
    if (visit.treatment_done) {
        doc.text(`Treatment: ${visit.treatment_done}`, 15, currentY);
        currentY += 6;
    }
  }

  // Rx Symbol
  doc.setFontSize(24);
  doc.setTextColor(37, 99, 235);
  doc.setFont('helvetica', 'bold');
  doc.text('Rx', 15, 105);

  // Medicines Section
  doc.setFontSize(12);
  doc.setTextColor(17, 24, 39);
  doc.text('PRESCRIPTION', 15, 115);

  const medicineStr = visit?.medicine_prescribed || patient.medicine_prescribed;
  const medicines = medicineStr ? medicineStr.split('\n').filter(m => m.trim()) : [];
  
  if (medicines.length > 0) {
    (doc as any).autoTable({
      startY: 120,
      head: [['#', 'Medicine & Dosage']],
      body: medicines.map((m, i) => [i + 1, m]),
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235], textColor: [255, 255, 255] },
      styles: { fontSize: 10, cellPadding: 5 },
      columnStyles: { 0: { cellWidth: 15 } }
    });
  } else {
    doc.setFontSize(10);
    doc.setTextColor(156, 163, 175);
    doc.text('No medicines prescribed.', 15, 125);
  }

  // Notes Section
  const finalY = (doc as any).lastAutoTable?.finalY || 135;
  const notesStr = visit?.notes || patient.notes;
  if (notesStr) {
    doc.setFontSize(12);
    doc.setTextColor(17, 24, 39);
    doc.setFont('helvetica', 'bold');
    doc.text('NOTES / INSTRUCTIONS', 15, finalY + 15);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(75, 85, 99);
    const splitNotes = doc.splitTextToSize(notesStr, pageWidth - 30);
    doc.text(splitNotes, 15, finalY + 22);
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setDrawColor(229, 231, 235);
  doc.line(15, pageHeight - 30, pageWidth - 15, pageHeight - 30);
  
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text('Generated by IntelliDent - Dental Management Platform', pageWidth / 2, pageHeight - 20, { align: 'center' });
  doc.text('Please follow the instructions carefully. Follow-up as advised.', pageWidth / 2, pageHeight - 15, { align: 'center' });

  // Save the PDF
  const fileName = `Prescription_${patient.name.replace(/\s+/g, '_')}_${visit?.date || patient.date}.pdf`;
  doc.save(fileName);
};
