import jsPDF from 'jspdf';
import 'jspdf-autotable';
import type { Patient, Visit, ClinicInfo } from '@/types';

export const generatePrescriptionPDF = (patient: Patient, clinic: ClinicInfo, visit?: Visit) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header - Clinic Info
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235); // primary color #2563eb
  doc.setFont('helvetica', 'bold');
  doc.text(clinic.clinic_name || 'IntelliDent Clinic', pageWidth / 2, 20, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // gray-500
  doc.setFont('helvetica', 'normal');
  const clinicSubHeader = `${clinic.address || ''}${clinic.phone ? ' | Phone: ' + clinic.phone : ''}${clinic.email ? ' | Email: ' + clinic.email : ''}`;
  doc.text(clinicSubHeader, pageWidth / 2, 28, { align: 'center' });

  // Line separator
  doc.setDrawColor(229, 231, 235);
  doc.line(15, 35, pageWidth - 15, 35);

  // Patient Info
  doc.setFontSize(12);
  doc.setTextColor(17, 24, 39); // gray-900
  doc.setFont('helvetica', 'bold');
  doc.text('PATIENT INFORMATION', 15, 45);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Name: ${patient.name}`, 15, 52);
  doc.text(`Age/Gender: ${patient.age || 'N/A'}Y / ${patient.gender || 'N/A'}`, 15, 58);
  doc.text(`Patient ID: ${patient.patient_id}`, 15, 64);
  
  const dateStr = visit?.date || new Date().toISOString().split('T')[0];
  const doctor = visit?.doctor || clinic.owner_name || 'N/A';
  
  doc.text(`Date: ${new Date(dateStr).toLocaleDateString()}`, pageWidth - 15, 52, { align: 'right' });
  doc.text(`Doctor: ${doctor}`, pageWidth - 15, 58, { align: 'right' });

  if (visit?.tooth_number) {
    doc.text(`Tooth: ${visit.tooth_number}`, pageWidth - 15, 64, { align: 'right' });
  }

  // Clinical Details
  if (visit?.clinical_findings || visit?.procedure_notes) {
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('CLINICAL DETAILS', 15, 75);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    let currentY = 81;
    if (visit.clinical_findings) {
        const splitFindings = doc.splitTextToSize(`Findings: ${visit.clinical_findings}`, pageWidth - 30);
        doc.text(splitFindings, 15, currentY);
        currentY += (splitFindings.length * 5);
    }
    if (visit.procedure_notes) {
        const splitProcedure = doc.splitTextToSize(`Procedure: ${visit.procedure_notes}`, pageWidth - 30);
        doc.text(splitProcedure, 15, currentY);
        currentY += (splitProcedure.length * 5);
    }
  }

  // Rx Symbol
  doc.setFontSize(24);
  doc.setTextColor(37, 99, 235);
  doc.setFont('helvetica', 'bold');
  doc.text('Rx', 15, 105);

  // Medicines Section
  doc.setFontSize(12);
  doc.setTextColor(17, 24, 39);
  doc.text('PRESCRIPTION', 15, 115);

  const medicineStr = visit?.medicine_prescribed;
  const medicines = medicineStr ? medicineStr.split('\n').filter((m: string) => m.trim()) : [];
  
  if (medicines.length > 0) {
    (doc as any).autoTable({
      startY: 120,
      head: [['#', 'Medicine & Dosage']],
      body: medicines.map((m: string, i: number) => [i + 1, m]),
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235], textColor: [255, 255, 255] },
      styles: { fontSize: 10, cellPadding: 5 },
      columnStyles: { 0: { cellWidth: 15 } }
    });
  } else {
    doc.setFontSize(10);
    doc.setTextColor(156, 163, 175);
    doc.text('No medicines prescribed.', 15, 125);
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setDrawColor(229, 231, 235);
  doc.line(15, pageHeight - 30, pageWidth - 15, pageHeight - 30);
  
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text('Generated by IntelliDent - Dental Management Platform', pageWidth / 2, pageHeight - 20, { align: 'center' });
  doc.text('Please follow the instructions carefully. Follow-up as advised.', pageWidth / 2, pageHeight - 15, { align: 'center' });

  // Save the PDF
  const fileName = `Prescription_${patient.name.replace(/\s+/g, '_')}_${dateStr}.pdf`;
  doc.save(fileName);
};
