import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { Patient } from '@/types';

interface ClinicInfo {
  clinic_name: string;
  owner_name: string;
  phone: string;
  address: string;
  email: string;
}

export const generatePrescriptionPDF = (patient: Patient, clinic: ClinicInfo) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header - Clinic Info
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235); // primary color #2563eb
  doc.setFont('helvetica', 'bold');
  doc.text(clinic.clinic_name || 'IntelliDent Clinic', pageWidth / 2, 20, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139); // gray-500
  doc.setFont('helvetica', 'normal');
  const clinicSubHeader = `${clinic.address || ''}${clinic.phone ? ' | Phone: ' + clinic.phone : ''}${clinic.email ? ' | Email: ' + clinic.email : ''}`;
  doc.text(clinicSubHeader, pageWidth / 2, 28, { align: 'center' });

  // Line separator
  doc.setDrawColor(229, 231, 235);
  doc.line(15, 35, pageWidth - 15, 35);

  // Patient Info
  doc.setFontSize(12);
  doc.setTextColor(17, 24, 39); // gray-900
  doc.setFont('helvetica', 'bold');
  doc.text('PATIENT INFORMATION', 15, 45);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Name: ${patient.name}`, 15, 52);
  doc.text(`Age/Gender: ${patient.age}Y / ${patient.gender}`, 15, 58);
  doc.text(`Patient ID: ${patient.patient_id}`, 15, 64);
  
  doc.text(`Date: ${new Date(patient.date).toLocaleDateString()}`, pageWidth - 15, 52, { align: 'right' });
  doc.text(`Doctor: ${patient.doctor || clinic.owner_name || 'N/A'}`, pageWidth - 15, 58, { align: 'right' });

  // Rx Symbol
  doc.setFontSize(24);
  doc.setTextColor(37, 99, 235);
  doc.setFont('helvetica', 'bold');
  doc.text('Rx', 15, 80);

  // Medicines Section
  doc.setFontSize(12);
  doc.setTextColor(17, 24, 39);
  doc.text('PRESCRIPTION', 15, 90);

  const medicines = patient.medicine_prescribed ? patient.medicine_prescribed.split('\n').filter(m => m.trim()) : [];
  
  if (medicines.length > 0) {
    (doc as any).autoTable({
      startY: 95,
      head: [['#', 'Medicine & Dosage']],
      body: medicines.map((m, i) => [i + 1, m]),
      theme: 'striped',
      headStyles: { fillColor: [37, 99, 235], textColor: [255, 255, 255] },
      styles: { fontSize: 10, cellPadding: 5 },
      columnStyles: { 0: { cellWidth: 15 } }
    });
  } else {
    doc.setFontSize(10);
    doc.setTextColor(156, 163, 175);
    doc.text('No medicines prescribed.', 15, 100);
  }

  // Notes Section
  const finalY = (doc as any).lastAutoTable?.finalY || 110;
  if (patient.notes) {
    doc.setFontSize(12);
    doc.setTextColor(17, 24, 39);
    doc.setFont('helvetica', 'bold');
    doc.text('NOTES / INSTRUCTIONS', 15, finalY + 15);
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(75, 85, 99);
    const splitNotes = doc.splitTextToSize(patient.notes, pageWidth - 30);
    doc.text(splitNotes, 15, finalY + 22);
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setDrawColor(229, 231, 235);
  doc.line(15, pageHeight - 30, pageWidth - 15, pageHeight - 30);
  
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text('Generated by IntelliDent - Dental Management Platform', pageWidth / 2, pageHeight - 20, { align: 'center' });
  doc.text('Please follow the instructions carefully. Follow-up as advised.', pageWidth / 2, pageHeight - 15, { align: 'center' });

  // Save the PDF
  doc.save(`Prescription_${patient.name.replace(/\s+/g, '_')}_${patient.patient_id}.pdf`);
};
